name: Build Debian Package

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  debian:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install build deps
        run: |
          sudo apt-get update
          sudo apt-get install -y devscripts debhelper dh-python python3-all python3-setuptools

      - name: Build .deb
        run: |
          debuild -us -uc

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: debian-artifacts
          path: ../cli-typer_* 

